### PR TITLE
Interpret block element

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by gigaSproule** [comment]
Can you add some assertions in the tests? I know the tests aren't great now regarding this, but it would be good to start improving them as we go along. At the moment, the tests don't throw an exception when reading in the report, but nor are we asserting that the correct value is recorded.

**Comment by pzygielo** [comment]
As shown by my first commit 92f85e9287c07c32150cb46683c672884f93fbc9 - `MutationReportTest` fails already (with `MUTATIONS` updated with new element). Also - other tests pass, that show that *missing* `block` does not cause problems on digesting xml. Thus IMO extended (ie. with this new element) mutations report is covered. 
Please point me to what else would you like me to check.

**Comment by gigaSproule** [comment]
I'll merge this in, but I feel like the tests (as a whole, not your piece of work) needs to be improved.

**Comment by pzygielo** [comment]
Reported also as [JENKINS-49891](https://issues.jenkins-ci.org/browse/JENKINS-49891).

**Pull request merged**
