### PR TITLE
Kill ratio is NaN%

### PR DESCRIPTION
**Pull request by rodripv**
When the mutations.xml report has the tag <description> the jenkins task prints "Kill ratio is NaN% (0  0)" and changes the build result to failure

### CODE REVIEW

**Comment by Prifiz** [comment]
@gigaSproule, hello.
As I can see, this fix was merged but remains unreleased.
Could you please perform the release for us to use the fix?

**Comment by gigaSproule** [comment]
Will do. Just had a build running on the jenkins where I work to make sure there weren't any issues. None seen so far so I think it's ok to release.

**Comment by Prifiz** [comment]
@gigaSproule, thanks!
Is it possible to make a release today or tomorrow? It's very important for us.

**Comment by gigaSproule** [comment]
Patience patience :stuck_out_tongue:

Just getting to grips with how the Jenkins plugins are released. Hopefully get it done tonight (UK time).

**Comment by gigaSproule** [comment]
Finally got to a point where it was starting to upload and then got unauthorised... Slightly annoyed as it's 1am, but never mind, I'll sort it out tomorrow (today).

**Comment by daniel-beck** [comment]
@gigaSproule 

> unauthorised

Please note 403 Forbidden is a permissions issue that would be resolved by the linked PR; 401 Unauthorized means that Maven doesn't send credentials. Test with `mvn deploy` of a snapshot, which everyone is allowed to do. [See this wiki page for solutions](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Workingaroundcommonissues).

**Comment by gigaSproule** [comment]
@daniel-beck Thanks for that. I'm sure I will run into that issue next, but I noticed that I hadn't actually created the PR anyway, so it had to be done either way.

**Comment by Prifiz** [comment]
@gigaSproule, hi!
Are there any updates about this issue?

**Comment by gigaSproule** [comment]
1.0-16-SNAPSHOT is pushed (http://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/pitmutation/), but there's not been any movement on the other PR

**Comment by Prifiz** [comment]
Can you release the version 1.0-16 with only current PR?
The other PR may not be updated during undefined time and it blocks the version. Is it possible to put it off until the next release?

**Comment by gigaSproule** [comment]
When I said other PR, I meant [this one](https://github.com/jenkins-infra/repository-permissions-updater/pull/490) which gives me permissions to push a release.

**Pull request merged**
